### ISSUE TITLE
Check range of cluster in the methods

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#105]
The method which creates and optimal number of cluster is not working.

Test:
Crop: African yean been
Method: normal
Indicators: Drought Tolerance
Range of cluster: 6 - 10

Answer: 3 clusters

![image](https://user-images.githubusercontent.com/4921829/138460175-00a4f6b4-b13f-457c-ae02-1f8d02a05bf5.png)

**Comment by khadijaAouzal** [comment]
I applied the algorithm to those data and for that range [6 - 10]. The result contains 6 clusters:

![image](https://user-images.githubusercontent.com/23177635/138692245-4a8a8cd6-12fb-480e-8a3c-14e7e10586ea.png)

**Comment by stevensotelo** [comment]
@juangarc 

- He fixed the way how he sent parameters to the function
- 
![image](https://user-images.githubusercontent.com/4921829/139440480-e61637e6-c0c1-4958-9f4a-5a5186d09cd4.png)
