### ISSUE TITLE
Add help button

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#112]
@juangarc 

- [x] Add button to help users. It should redirect to a new tab for methodology and glossary

@khadijaAouzal 

- [x] She add description where the button should be located

**Comment by khadijaAouzal** [comment]
![image](https://user-images.githubusercontent.com/23177635/139460334-c539bdd7-aacd-4519-b32c-729e669e353b.png)

 Here, we already have the help icons but do not redirect to the methodologies tab:  

![image](https://user-images.githubusercontent.com/23177635/139460587-2cc2ad1c-d69a-4433-a66c-41ef3ed3d478.png)

For the glossary, I suggest to add the help button in the indicators section. For example:

![image](https://user-images.githubusercontent.com/23177635/139462062-b6e21243-278b-469e-a8a7-c64ff84f9a57.png)

**Comment by stevensotelo** [comment]
@juangarc 

- He included the button
- [x] He should fix the position in the website. Follow the @khadijaAouzal recommendations

@khadijaAouzal 
- She sent the recommendation

**Comment by stevensotelo** [comment]
@juangarc 

- He solved the issue

![image](https://user-images.githubusercontent.com/4921829/141474005-3155777e-d15d-422c-854b-d6c855dc7289.png)
