### ISSUE TITLE
Implement summary with improvements in basic search results

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#120]
![image](https://user-images.githubusercontent.com/36042734/140517400-02986d8e-1949-4c4e-ab8b-c821d0ea9dba.png)

**Comment by juangarc** [comment]
![image](https://user-images.githubusercontent.com/36042734/140518395-4344eb17-233a-49a9-b765-8b0805e48968.png)

**Comment by stevensotelo** [comment]
@juangarc 

- He implemented the dashboard
