### ISSUE TITLE
Join the components of the results in the basic query (Accessions, Maps)

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#123]

**Comment by stevensotelo** [comment]
@juangarc 

- He joined the components in the same
- [x] He should fix the distribution of the components:
pie | summary table
map
accessions
- [x] Add message on top pie chart that indicates to users: click on the cluster to see the accessions

**Comment by juangarc** [comment]
- Fixed the distribution of the componentes
- Added the message

- [ ]  I should check the amount of accessions in pie chart.
