### ISSUE TITLE
Rename the categories of indicators

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#129]

**Comment by stevensotelo** [comment]
@juangarc updated the categories indicators, however he should updated the category "indicators photoperiod"

![image](https://user-images.githubusercontent.com/4921829/141473910-578c31f4-138c-4160-8917-f00578ace448.png)

**Comment by juangarc** [comment]
![image](https://user-images.githubusercontent.com/36042734/142211512-5676c395-c9fd-422c-911b-ddacd0364aaf.png)
