### ISSUE TITLE
Generate button of random selection and core collection not working

### ISSUE THREAD

**Issue by khadijaAouzal** [CIAT-DAPA/subsets_genebank_accessions#138]
The GENERATE button is not clickable in random selection and in core collection:

![image](https://user-images.githubusercontent.com/23177635/184156205-0d9c8148-f842-4025-90cb-98f64e6edd8f.png)

**Comment by victor-993** [comment]
the version currently deployed in genesys does not work, this has been corrected in more recent versions.
