### ISSUE TITLE
Problems for select crop

### ISSUE THREAD

**Issue by bmora-0110** [CIAT-DAPA/subsets_genebank_accessions#141]
El problema es el siguiente: Cuando selecciono el cultivo en la pagina principal y posteriormente voy a la pestaña de subsetting tool debo volver a seleccionar el cultivo.  Si no lo selecciono la Pag se queda cargando por siempre. Me parece que seria genial que el cultivo que se selecciona en la pagina principal permanezca fijo mientras navego en  subsetting, de no ser posible colocar un mensaje de alerta para que el usuario lo vuelva a seleccionar el cultivo en subsetting .

**Comment by victor-993** [comment]
Esto sucede cuando no se selecciona un cultivo en especifico y el filtro de las accesiones se realiza por otro metodo como coincidencia de texto, una taxonomia espedifica entre otros esto hacia que al momento de utilizar el servicio mapInfo de Genesys para recuperar la informacion de las accesiones de cada cluster generado no obtenga la informacion correcta

Se soluciono generando clusters para un unico culivo que se nombra como "Custom" y al momento de hacer el llamado al servicio de mapInfo no se especifica el cultivo solo se envian los tileIndexes

![image](https://user-images.githubusercontent.com/63070035/184420435-c6c6b912-590a-4f0a-9c58-0a1aa9128afa.png)
![image](https://user-images.githubusercontent.com/63070035/184420583-49ccf3bf-8406-48f6-a305-487d16e19499.png)
