### ISSUE TITLE
categories in soil indicators

### ISSUE THREAD

**Issue by bmora-0110** [CIAT-DAPA/subsets_genebank_accessions#143]
Se deberian mostrar las categorias de las variables categoricas esto  con el fin de que el usuario vea que son variables cualitativas y cuales son sus clases. 
![image](https://user-images.githubusercontent.com/75317498/184178261-7a9c1f92-232f-480e-9ae0-ec3fc1f2b2db.png)

**Comment by victor-993** [comment]
La version que se encuentra desplegada en https://sandbox.genesys-pgr.org/ cuenta con algunos conflictos en las versiones mas recientes este bug ya se encuentra solucionado.

![image](https://user-images.githubusercontent.com/63070035/184420074-c158ddb7-0928-4809-968a-32167e174374.png)
