### ISSUE TITLE
HUS016 - Share outputs via URL

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#18]
**Description**

As an Advanced user in the web module, I want to be able share accessions subsets outputs via URL, which generates a secure link so that the user can access the outputs of created accessions subset.

**Acceptance criteria**

**Stage 1 - Generate URL:** Once the advanced user creates a Genebank accessions subset, the system must generate a new custom URL so that the user can share it.

**Comment by jramirezv** [comment]
Looks ok
