### ISSUE TITLE
HUS018 - Area selection on a map

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#20]
**Description**

As an Advanced user in the web module, I want to be custom my accessions subsets selecting an area on the map and that the system filters the subset only with the accessions that have match with the location information of selected area.

**Acceptance criteria**
1. The system must have a rectangle with the world map where the user can draw the preference area. 
2. The system must have a section where the user can filter according country, state or county 

**Exceptions**
3. The user must select a valid area.

**Comment by jramirezv** [comment]
Need to add the type of selection: (1) admin level (country, state, county); (2) a rectangle that user can draw; or (3) a custom shape that the user can draw.
