### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#23]
Create a web API to the tool that allows the communication between the indicators database and website.

- [x] The web API must allow to query each collection present in the indicators database though a URI or endpoint that be identified easy for the collection to query. i.e. if I need to query the data corresponding to accessions, the URI must contain in your endpoint the identifier .../accessions/

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He finished the model in python

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] He is working in the abiotic indicator query
- [ ] The format for the input query should be: [{ indicators: ["PC_95",...], accessions: ["64654","8979"], parameters: [{country: "India", ...}]}]
- [ ] Add input for the method for custom indicators (file)
