### ISSUE TITLE
Master Script

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#25]
Master script is responsible for executing the processes that build indicators. This orchestrates the construction of indicators according to the given request, here users must specify the type of indicators you want to build, then the script will search the Genesys API for the main data of the accessions (passport data) and then send them to the construction of the indicator through the Parallelization Component according to the type of indicator set previously identified, once the indicator has done the process, it returns the calculated indicator of the accession. This component saves data of indicators into the indicator database.

**Comment by stevensotelo** [comment]
@juangarc 

- [x] the first version is in the repository
- [x] is pending updated some codes from other modules

**Comment by stevensotelo** [comment]
@stevensotelo @bmora-0110 @juangarc 

We trying to run the docker image in windows server, however it didn't work. Next step is to try implementing in Linux server

- [x] Windows.  Didn't work because shared folder can not be connected to docker in windows
- [x] Linux server.

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He deployed the images in Linux server and it is working


@brayan9487 

- [x] Checking some issues in the source code. It is not working well
- [x] He passed data for indicators (ndws, ndwl and cdd) to @juangarc  for Africa

**Comment by stevensotelo** [comment]
@juangarc 

- He is working in the web page, it is a priority for now

**Comment by stevensotelo** [comment]
@juangarc and @bmora-0110 

- The code is running in linux right now

@juangarc 

- [x] Still pending to add new source code into the master script

**Comment by stevensotelo** [comment]
@juangarc

- He implemented generic indicators into the master script
- [x] He should add code for generic specific per crop (@bmora-0110  hasn't developed yet)
- [x] He should implement log

**Comment by stevensotelo** [comment]
@juangarc

- He implemented the log function
- [x] He should add code for generic specific per crop (@bmora-0110 hasn't developed yet)

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He should add code for generic specific per crop (@bmora-0110 hasn't developed yet)

**Comment by stevensotelo** [comment]
@juangarc

- [x] He should add code for generic specific per crop (@bmora-0110 hasn't developed yet)

**Comment by stevensotelo** [comment]
@juangarc

- [x] He should add code for generic specific per crop (@bmora-0110 hasn't developed yet)
- [ ] He should implement code of the extracted value indicator. @bmora-0110 should says, it is ok

**Comment by stevensotelo** [comment]
It is in stand by for now, while @bmora-0110 debugs the source code

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He should add code for generic specific per crop (@bmora-0110 already developed the code)
- [ ] He should implement code of the extracted value indicator. (@bmora-0110 already developed the code)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] He is pending to send data to @juangarc

**Comment by stevensotelo** [comment]
@bmora-0110 
- He updated the source code

@juangarc 
- [x] He should add code for specific per crop indicator
- [ ] He should implement code of the extracted value indicator

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He should add code for specific per crop indicator
- [ ] He should implement code of the extracted value indicator

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] He should implement code of the extracted value indicator
- He added the code for generic indicator

@bmora-0110 
- [x] He should add the function for extracted value indicator

**Comment by stevensotelo** [comment]
@bmora-0110 
- [x] He should update the source code in github

**Comment by stevensotelo** [comment]
@bmora-0110

- [x] He should update the source code in github

**Comment by bmora-0110** [comment]
I change the laptop, and I had problems installing git (administrator permissions). But send the codes that Juan Camilo needs to the Skype chat.

**Comment by stevensotelo** [comment]
@bmora-0110 

- He sent tha source code to @juangarc 

@juangarc 
- [x] He should implement the new function in the master script

**Comment by juangarc** [comment]
I implemented the source code in the master script
