### ISSUE TITLE
Generator passport indicator

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#26]
Generator passport indicator is a module to index the accessions depending of country, biological status, geographic position, altitude andinstitution. It extracts relevant data from accessions to build passports indicators. It set the pixel index for all accession which have coordinates, it allows that the filtering process can be according to the indicators. The accessions are extracted from Genesys through its Web API.

**Comment by juangarc** [comment]
@khadijaAouzal, Can you help me changing the fields names of passport indicators? The new fields name are:
    name
    number
    acq_date
    aegis
    available
    coll_date
    country_code
    country_name
    country_region_name
    samp_stat
    crop_name
    doi
    historic
    id 
    institute_fullname
    institute_acronym 
    geo_lon
    geo_lat 
    geo_ele 
    cellid

**Comment by khadijaAouzal** [comment]
@juangarc Yes, for sure.  
I see that some fields that might be important for filtering are missing, such as those related to taxonomy: **genus**, **species**, **subtaxa**, **taxonName**, etc.  
What do you think? Will they be necessary?

**Comment by juangarc** [comment]
Yes, great idea, I consider we could add them.

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She was atttending some issues about warnings

- [x] Pending to validate the script for some crops

**Comment by juangarc** [comment]
- [x] She is working in a issue about logging

**Comment by stevensotelo** [comment]
I reopened this issue because we have some problems

@juangarc

- [x] Should fix the function to import data. @khadijaAouzal adviced him to remove the try catch function

**Comment by stevensotelo** [comment]
@juangarc

- He followed up the indications of @khadijaAouzal. He removed the try-catch function
- [x] He should send the crop name in which he is having problems with the download

@khadijaAouzal 

- [x] Check what's going wrong with some crops and the function for downloading data from genesys

**Comment by juangarc** [comment]
![image](https://user-images.githubusercontent.com/36042734/112697855-7703c700-8e56-11eb-8a98-742b2b3dd608.png)

This is the issue I have when I run the script for some crops, in the example I was obtaining data for Maize crop

**Comment by stevensotelo** [comment]
@juangarc and @khadijaAouzal 

- They solved the issue with passports data. It was about the try-catch function
