### ISSUE TITLE
Generator generic indicators 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#28]
Generator generic indicators is a module which should calculates indicators for all world. This module uses Module time series in order to calculate these indicators. It requires of raster base, which allows to identify the id of all pixels.

**Comment by stevensotelo** [comment]
Next week @bmora-0110 will finish this script next week

**Comment by stevensotelo** [comment]
@juangarc @bmora-0110 @stevensotelo 

- [x] @bmora-0110 created a base functions to run the process
- [x] Check the source code in order for refactoring some functions

**Comment by stevensotelo** [comment]
The source code was implemented fully for some indicators

- [x] Windows implementation is ready for some indicators
- [x] Fix some issues about Linux implementation
- [x] Pending: water logging and solar radiation

**Comment by stevensotelo** [comment]
Still the source code is not running well

@bmora-0110 @juangarc 

- [x] They will try to solve some issues that are happening in linux server, if the wont solve for Wednesday the start to execute into Windows server while they can solve for linux

**Comment by juangarc** [comment]
- He has data of any countries (Europe, Oceania)

- [x]  He must optimize the water logging
- [x]  He must solve the coordinates for raster base

**Comment by stevensotelo** [comment]
@brayan9487 

- [x] Still is pending linux problems
- [x] Still is pending optimize the water logging (it is testing code)

All other generic indicators are ready

**Comment by stevensotelo** [comment]
@bmora-0110 and @juangarc 

- They fixed the issues with linux. Now the source code is running in linux

@brayan9487 

- He updated the source code for the water logging indicator
- [x] The source code is pending to test (actually it is runnning in windows, however it is not working in linux)
- [x] The water logging should work in linux 
- [x] The source code is pending to update in Github

**Comment by stevensotelo** [comment]
@bmora-0110 and @juangarc

- They solved the issues with linux enviroment

@bmora-0110 

- [x] The watter logging is still pending
- [x] The source code is pending to update in Github

**Comment by stevensotelo** [comment]
@bmora-0110 

- He solved the issues with water logging in linux
- [x] The source code is pending to update in Github

@juangarc 

- [x] He is helping to @bmora-0110 to solve the issue with updating source code in github

**Comment by stevensotelo** [comment]
@bmora-0110 and @juangarc 

- They updated the Github repository
