### ISSUE TITLE
Generator specific per crops indicator 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#29]
Generator specific per crops indicator is a module which calculates indicators for specific crops. It requires a special parametrization for each crop, further requires to establish which is the grown up areas for those crops. It uses Module time series in order to calculate these indicators.

**Comment by stevensotelo** [comment]
@bmora-0110:
- [x] ask to @jramirezv and zack if this types of indicators should be work either season or by all year
- [x] ask for threshold for crops, because these parameters are needed to calculate indicators. Mainly, the genebanks curators can help us to define these parameters

**Comment by stevensotelo** [comment]
@bmora-0110 

- He started to develop this component
- He dind't ask to zack and julian, he realize that he should calculate the indicators month by month, because CRW
- [x] He is using ecocrops threashold in oder to create a base for the indicators
- [x] He should take some threashold for crops that are into the **survey**

**Comment by stevensotelo** [comment]
@bmora-0110 

- He is working in create crop areas

@juangarc 

- [x] He should share information with @bmora-0110 about genesys accessions (cell_id)
- [x] He should update the raster base and import again the accessions with the module of passport indicators

**Comment by stevensotelo** [comment]
@bmora-0110 

- He has problem with the following crops: mussa collection, andins crops and andin tubbers. Those crops are not in maps spam
- He took thresholds from survey
- He shared the list of the crops to @juangarc, in order to prioritize the list of the crops
- [x] He should ask to @jramirezv  what we should do with these crops

@juangarc 

- He updated the raster base and reimport the accessions with the new cell ids
- [x] Still is pending to send information to brayan about genesys accessions in order that @bmora-0110 can creates the areas per crop

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He should share information with @bmora-0110 about genesys accessions (cell_id) (Still pending)
- [x] He implemented a table with the list of crops that has sent to @bmora-0110 

@bmora-0110 

- He wrote a email to @jramirezv asking about what we should do with the crops: mussa collection, andins crops and andin tubbers, however he hasn't received an answer
- [x] Pending get the answer from @jramirezv

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Still is pending to send information to brayan about genesys accessions in order that @bmora-0110 can creates the areas per crop
- He prioritized the crop list for @bmora-0110 

@bmora-0110

- [x] Pending get the answer from @jramirezv

**Comment by stevensotelo** [comment]
@juangarc 

- He Sent the information about of accession to @bmora-0110, in order to he can create the grown up areas for crops

@bmora-0110 

- [x] Pending get the answer from @jramirezv
- [x] Pending to create grown up areas for crops with the information

**Comment by stevensotelo** [comment]
@bmora-0110 

- He got an answer from Julian. he should join two crops in order to create a grown up areas for mussa collections.
- He developed the script, actually he is testing the code
- [x] Actually just 5 crops are pending to mix with maps spam database with genesys data
- [x] Create a issue with a table similiar to generic indicators (processing)

**Comment by bmora-0110** [comment]
|Crop|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Beans|---|---|----|----|---|---|
|Forages|---|---|----|----|----|---|
|Cassava|---|---|---|---|---|---|
|Banana|---|---|---|---|---|---|
|Wheat|---|---|---|---|---|---|
|Maize|---|---|---|---|---|---|
|Potato|---|---|---|---|---|---|
|Sweet potato|---|---|---|---|---|---|
|Andean crops|---|---|---|----|---|---|
|Rice|---|---|---|---|---|---|
|Barley|---|---|---|---|---|---|
|Sorghum|---|---|---|---|---|---|
|Pearl Millet|---|---|---|---|---|---|
|Cowpea|---|---|---|---|---|---|
|Yam|---|---|---|---|---|---|
|Soybean|---|---|---|---|---|---|

**Comment by stevensotelo** [comment]
@bmora-0110 

- He created a table to follow the progress
- [x] He is pending to continue the development of the source code. He is waiting for new file from @juangarc

**Comment by stevensotelo** [comment]
@bmora-0110 

- He mixed the 5 crops with maps spam database with genesys data
- [x] He is running the script

@juangarc 

- He sent the file with information about the coordinates of the crops

**Comment by stevensotelo** [comment]
@bmora-0110 

- He has developed all functions to run this process
- [x] He should update the source code in github

**Comment by stevensotelo** [comment]
@bmora-0110
- He updated the source in Github
- [x] Update source code for helpers code

**Comment by stevensotelo** [comment]
@bmora-0110 
- [x] Update source code for helpers code

**Comment by stevensotelo** [comment]
@bmora-0110

- [x] Update source code for helpers code

**Comment by stevensotelo** [comment]
@bmora-0110
- [x] Update source code for helpers code

**Comment by stevensotelo** [comment]
@bmora-0110 
- He updated the repository
