### ISSUE TITLE
HUS002 Build abiotic indicators.

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#3]
**Description**
As an administrator user, I want to   be able build a set of biotic indicators for each accession, with which   latterly the users will may to create Genebank accessions subsets from   filters based in them.

**Acceptance criteria**

- [ ] 1. The file generated must be in Shapefile format.

- [ ] **Stage 1 - Number of water stress day:** To   create the number of water stress day indicator for each accession the   administrator user must have a file with the following fields (cellid, lon,   lat, ndws, collection date),  once him   had filled out it, the administrator user will proceed to select it in the   section abiotic indicators number of water stress day and latterly him will   run the script that build them. 

- [ ] **Stage 2 - Number of days with waterlogging:** To create the number of days with   waterlogging indicator for each accession the administrator user must have a   file with the following fields (cellid, lon, lat, ndwl, collection   date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators number of days with waterlogging and latterly him will run the   script that build them.     

- [ ] **Stage 3 - Extreme daily precipitation:** To create the extreme daily   precipitation indicator for each accession the administrator user must have a   file with the following fields (cellid, lon, lat, p95, collection date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators extreme daily precipitation and latterly him will run the script   that build them.            

- [ ] **Stage 4 - Average precipitation:** To create the average precipitation indicator   for each accession the administrator user must have a file with the following   fields (cellid, lon, lat, ravg, collection date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators average precipitation and latterly him will run the script that   build them.          

- [ ] **Stage 5 - Number of days high daytime temperature:** To create the number of days   high daytime temperature indicator for each accession the administrator user   must have a file with the following fields (cellid, lon, lat, nth, collection   date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators number of days high daytime temperature and latterly him will run the script that build  them         

- [ ] **Stage 6 - Number of days with low minimum temperatures:** To   create the number of days with low minimum temperature indicator for each   accession the administrator user must have a file with the following fields   (cellid, lon, lat, ntl, collection date), once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators number of days with low minimum temperature and latterly him will run the script that build them.            

- [ ] **Stage 7 - Average minimum temperature:** To create the average   minimum temperature indicator for each accession the administrator user must   have a file with the following fields (cellid, lon, lat, tn, collection   date), once him had filled out it, the administrator user will proceed to select   it in the section abiotic indicators average minimum temperature and latterly   him will run the script that build them.           

- [ ] **Stage  8 - Average maximum temperature:** To create the average maximum   temperature indicator for each accession the administrator user must have a   file with the following fields (cellid, lon, lat, tx, collection date), once   him had filled out it, the administrator user will proceed to select it in   the section abiotic indicators average maximum temperature and latterly him   will run the script that build them.          

- [ ] **Stage 9 - Average solar radiation:** To create the average solar radiation   indicator for each accession the administrator user must have a file with the   following fields (cellid, lon, lat, sr, collection date), once him had filled   out it, the administrator user will proceed to select it in the section   abiotic indicators average solar radiation and latterly him will run the   script that build them.              

- [ ] **Stage 10 - Monthly mean daylength:** To create the monthly mean daylength   indicator for each accession the administrator user must have a file with the   following fields (cellid, lon, lat, dl, collection date), once him had filled   out it, the administrator user will proceed to select it in the section   abiotic indicators monthly mean daylength and latterly him will run the   script that build them.                                                                                                                                                                                         

- [ ] **Stage 11 - Number of days with high VPD:** To create the number   of days with high VPD indicator for each accession the administrator user   must have a file with the following fields (cellid, lon, lat, nvpd4,   collection date), once him had filled out it, the administrator user will   proceed to select it in the section abiotic indicators number of days with   high VPD and latterly him will run the script that build them.       

- [ ] **Stage 12 - Average VPD:**  To create the   average VPD indicator for each accession the administrator user must have a   file with the following fields (cellid, lon, lat, vpd, collection date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators average VPD and latterly him will run the script that build them.

- [ ] **Stage 13 - Consecutive dry days:** To   create the consecutive dry days indicator for each accession the   administrator user must have a file with the following fields (cellid, lon,   lat, cdd, collection date), once him had filled out it, the administrator   user will proceed to select it in the section abiotic indicators consecutive   dry days and latterly him will run the script that build them.  

- [ ] **Stage 14 - Soil texture type:** To create the soil texture type indicator for   each accession the administrator user must have a file with the following fields   (cellid, lon, lat, texmht, collection date), once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators soil texture type and latterly him will run the script that build   them.     

- [ ] **Stage 15 - Bulk density:** To create the bulk density indicator for each   accession the administrator user must have a file with the following fields (cellid,   lon, lat, bldfie, collection date),    once him had filled out it, the administrator user will proceed to   select it in the section abiotic indicators bulk density and latterly him   will run the script that build them.

- [ ] **Stage 16 - Cation exchange capacity:** To create the cation exchange capacity   indicator for each accession the administrator user must have a file with the   following fields (cellid, lon, lat, cecsol, collection date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators cation exchange capacity and latterly him will run the script that   build them.

- [ ] **Stage 17 - Organic carbon content:** To create the organic carbon content   indicator for each accession the administrator user must have a file with the   following fields (cellid, lon, lat, orcdrc, collection date),  once him had filled out it, the   administrator user will proceed to select it in the section abiotic   indicators organic carbon content capacity and latterly him will run the   script that build them.

- [ ] **Stage 18 - Climate data:** To create the climate data indicator for each   accession the administrator user must have a file with  the following fields (Id_accesion, minimum   temperature, maximum temperature, solar radiation),  once him had filled out it, the   administrator user will proceed to select it in the section environmental   indicators climate data and latterly him will run the script that build   them.

- [ ] **Stage 19 - Successful   operation:** For each stage, if the operation flow is successful the system   shows a message indicating it.       

- [ ] **Stage 20 - Failed operation:** For each stage, if the file   structure isn't correctly, the system will show an exception with the   message: "The file structure isn't correct."    

- [ ] **Stage 21 - Missing value:** For each stage, if the file has a   column without value, the indicator for this accession won't create.  

- [ ] **Stage 22 - Generate logs file:**  For each   stage the system will generates a log file, which is described in the HUS007.

**Comment by khadijaAouzal** [comment]
Is it the administrator user who will build the set of indicators? Does this mean that the system needs the interaction of the administrator in each request? I think that the system should be autonomous in that

**Comment by stevensotelo** [comment]
> Does this mean that the system needs the interaction of the administrator in each request? I think that the system should be autonomous in that

Not really, the script should receive a stimulus, which can come from a user or a system

**Comment by stevensotelo** [comment]
@brayan9487:

- [x] has has installed docker, 

- [ ] Install docker image

- [ ] @juangarc will meet with @brayan9487 today and install the image.

- [x] he has an example of the genesys data that @khadijaAouzal sent us

**Comment by bmora-0110** [comment]
1. Make an inventory of what information is already calculated and then send it to Juan in the appropriate format.

2. Make a code for generic indicators and one for indicators specific to each crop.
