### ISSUE TITLE
Subsets DB 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#33]
Subsets DB contains data about user sessions, such as preferences, language, and other settings. It also saves information with custom URLs that refer to subsets of accessions and that users can share with others.

**Comment by stevensotelo** [comment]
@juangarc 

- He hasn't started yet, he is implementing a version in CIAT Servers

**Comment by stevensotelo** [comment]
@juangarc 

- He hasn't started yet, he is implementing a version in CIAT Servers

**Comment by stevensotelo** [comment]
@juangarc 

- He created a prototype of the schema. We will check it in order to validate and improve it

**Comment by juangarc** [comment]
![SubsetsDB](https://user-images.githubusercontent.com/36042734/119138414-7f682080-ba07-11eb-8137-9b1edffc44d5.jpg)

**Comment by stevensotelo** [comment]
@juangarc 

- He develop the schema of the database (mongo)
- [x] He should implement the schema into the app

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He develop the code into the subsets API, but he should add a new component, because it is not part of subsets API
- [x] He should implement the web interface

**Comment by stevensotelo** [comment]
@juangarc 
- He developed the Database
- He developed a API for Subsets DB
- He implemented the web interface
- He developed a custom login
- [x] He is working in the custom urls for the subsets
- [x] He should implement Genesys users API

**Comment by stevensotelo** [comment]
@juangarc 
- [x] He is working in the custom urls for the subsets
- [x] He should implement Genesys users API

**Comment by stevensotelo** [comment]
@juangarc 
- He developed the API for save custom urls
- [x] He is implementing a button to save the custom urls in the website

**Comment by stevensotelo** [comment]
@juangarc 

- He is implementing a button to save the custom urls in the website
