### ISSUE TITLE
Subsets API 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#34]
The Subsets API is a Web API, which contains a set of methods to create subsets of accessions based on indicators. The indicators can be previously calculated or custom datasets of the users. It is used like an access point to get access to subsets of accessions. This container just offers one method to obtain subsets of accession, this web method exposes receive a json string in which should be explicit parameters to build the subset.

**Comment by stevensotelo** [comment]
This week, we should define some features about database in order that the query can work with the database

**Comment by stevensotelo** [comment]
@juangarc 
It is in stand by

**Comment by stevensotelo** [comment]
@juangarc 

He is still working

**Comment by stevensotelo** [comment]
@juangarc 

- He implemented the services with a method to extract data from the database
- Only three conditions (filters) were implemented

- [x] Pending to add more filters

**Comment by juangarc** [comment]
- He is working in the connection of services with the front

**Comment by stevensotelo** [comment]
@juangarc has developed a version which can be review. Actually, the custom indicators is pending to implement, however other indicators are working

**Comment by stevensotelo** [comment]
We will implement two analysis methods

- [x] One variable
- [x] Multi-variable

**Comment by stevensotelo** [comment]
@juangarc 

- He tested the filter for variables, he said it is working
- The multivariable analysis will be developed by @khadijaAouzal

**Comment by stevensotelo** [comment]
@juangarc

- He integrated custom indicator into this module (moved from #31) [March 5]
- [x] He should test the integration with custom indicators
- [x] He should integrate the multivariable analysis into the subsets API, as soon @khadijaAouzal has a version.

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Pending to test the integration with custom indicators

**Comment by stevensotelo** [comment]
@juangarc 

- He implemented the custom indicators into the web API
- [x] He should integrate the multivariable analysis into the subsets API, as soon @khadijaAouzal has a version.

**Comment by stevensotelo** [comment]
@juangarc 
- [x] He should integrate the multivariable analysis into the subsets API, as soon @khadijaAouzal has a version.

**Comment by stevensotelo** [comment]
@juangarc 

- He update the microservice which get data into the database. It was because he updated the database schema in mongo
- [x] He should check the performance of this tool

**Comment by stevensotelo** [comment]
@juangarc 

- He is working in the services, it is because we updated the schema of the database
- [x] He still is working in the query to get data
- [x] He should check the performance of this tool
- [x] He should integrate the multivariable analysis into the subsets API, as soon @khadijaAouzal has a version.

**Comment by stevensotelo** [comment]
@juangarc 

- He solve the issue with query to get data
- He check the performance of this tool

@khadijaAouzal 

- [x] She will send the beta version to @juangarc next week in order to test it into the web api

**Comment by stevensotelo** [comment]
@juangarc
- [x] He should integrate the multivariable analysis into the subsets API, as soon @khadijaAouzal has a version.

@khadijaAouzal
- [x] She will send the beta version to @juangarc next week in order to test it into the web api

**Comment by stevensotelo** [comment]
@juangarc 
- He implemented the multivariable analysis into the web api

@khadijaAouzal 
- She sent the function of multivariable analysis to Camilo
