### ISSUE TITLE
SAD

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#38]
- [x] @khadijaAouzal will improve the explanation about extracted values
- [x] @bmora-0110 should add the oversea level indicator in the table of extracted values indicators

**Comment by khadijaAouzal** [comment]
@stevensotelo I have put some comments in the document, could you please look at them?

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x]  Will give us a explanation about how is the process to calculate indicators with statistical distribution

**Comment by stevensotelo** [comment]
- @bmora-0110 texted the paragraph for explaining how is the process to calculate indicators with statistical distribution
- @khadijaAouzal improved some paragraph into the document

**Comment by stevensotelo** [comment]
@stevensotelo and @khadijaAouzal 

- [x] Check the document and fix issues

**Comment by stevensotelo** [comment]
This is pending to check

**Comment by stevensotelo** [comment]
@stevensotelo and @khadijaAouzal

- [x] Check the document and fix issues

**Comment by stevensotelo** [comment]
@stevensotelo and @khadijaAouzal 

- The document was updated

@juangarc 

- He updated the chapter of the database
