### ISSUE TITLE
Raster base limitation

### ISSUE THREAD

**Issue by khadijaAouzal** [CIAT-DAPA/subsets_genebank_accessions#42]
The raster base we are working with does not cover all the coordinates available in the accessions data. This results in NA cellid even for non NA coordinates.

**Comment by stevensotelo** [comment]
@brayan9487 

- [x] Have to update the raster base. We need one which can cover all world

**Comment by stevensotelo** [comment]
@bmora-0110 

- He updated the file
- [x] He should send the file to @khadijaAouzal and @juangarc

**Comment by stevensotelo** [comment]
@bmora-0110 

- He fixed the raster base and shared the file with us
