### ISSUE TITLE
Generic indicators process

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#43]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|ndws|Ready|Ready|Ready|Ready|Ready|Ready|
|ndwl|Ready|Ready|Ready|Ready|Ready|Ready|
|p95|Ready|Ready|Ready|Ready|Ready|Ready|
|t_rain|Ready|Ready|Ready|Ready|Ready|Ready|
|tn|Ready|Ready|Ready|Ready|Ready|Ready|
|tx|Ready|Ready|Ready|Ready|Ready|Ready|
|sr|Ready|Ready|Ready|Ready|Ready|Ready|
|nvpd 4|Ready|Ready|Ready|Ready|Ready|Ready|
|vpd|Ready|Ready|Ready|Ready-|Ready|Ready|
|cdd|Ready|Ready|Ready|Ready|Ready|Ready|
|dl|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/110947686-79bad400-830e-11eb-9b7c-98af5c835d76.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] He has to update cell id for indicators which were calculated with the first version of the raster base

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/111789365-104b4000-888f-11eb-895a-6b1e5926a46d.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- He updated the cell id with the new raster base

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/112640096-02596a00-8e0f-11eb-8793-a24f02ec6ddc.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] He should check what is happening with  p95 and t_rain indicators in Africa.
- [x] Check the best way to calculate some other indicators (mean, std, slope)

@juangarc 

- [x] He should import the indicators to the database

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/114184213-31410700-990a-11eb-9eb5-fc1547940c54.png)

**Comment by stevensotelo** [comment]
@bmora-0110
- He solved the issue with p95 and t_rain indicators in Africa.
- The indicators (mean, std, slope) will be calculated by multivariable analysis (#44 )

@juangarc
- [x] Pending import the indicators to the database

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/115028780-e2a3e780-9e8a-11eb-9edf-f33a705cd04f.png)

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Pending to import data into database

**Comment by juangarc** [comment]
I'm working in order to import data into database (the process is very slow, but it is in progress)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/116699212-e9eaeb00-a98a-11eb-9535-d4045a962da0.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] He has a problem with memory in water logging indicators. He thinks that it could be by memory ram, actually brayan is working splitting the continents asia, north america and south america

@juangarc 

- [x] He still is importing data into database

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/117453445-95a3b600-af0a-11eb-8950-d101502a20a4.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- He solved the issue about memory capacity in the servers 

@juangarc 

- The issue about import data was moved to #49

**Comment by stevensotelo** [comment]
@bmora-0110 

- It is running in the servers

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121360803-5a761780-c8fa-11eb-9b19-8d20b360628b.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121691317-7f9a8f80-ca8c-11eb-9bec-83961b61f4a8.png)

**Comment by stevensotelo** [comment]
@bmora-0110 
- The water logging is finished
- [x] He should calculate the indicator (water balance) for ndws and ndwl

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/123429621-c27c5d00-d58c-11eb-8579-fbd5e2c7d298.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/124279687-688c1200-db0d-11eb-9c5a-9c3d9292d9bc.png)
