### ISSUE TITLE
Subsets web

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#45]
Implement a module frontend friendly with the users for that their can use the features of the applications.

**Comment by stevensotelo** [comment]
@juangarc 

- [ ] Develop new plots

![image](https://user-images.githubusercontent.com/4921829/111796372-1c86cb80-8896-11eb-8dcb-67d883b41c98.png)
![image](https://user-images.githubusercontent.com/4921829/111796413-26a8ca00-8896-11eb-902c-a786011db83d.png)

**Comment by khadijaAouzal** [comment]
This link can be helpful: https://www.influxdata.com/how-to-visualize-time-series-data/

**Comment by stevensotelo** [comment]
@juangarc 

- He implemented line chart in the website
- [x] He should implement two charts more for one variable

**Comment by stevensotelo** [comment]
@juangarc 

- [x] He still is working in the source code

**Comment by stevensotelo** [comment]
@juangarc 

- He added two new plots: lines and density
- [x] Start working with maps: show the position of the accessions
- [x] Add the button for importing custom data
- [x] <s>Start to develop the map selection for indicators</s> (We remove this issue for now- Analogues)

**Comment by juangarc** [comment]
- I worked in the maps component, I included the OSM library, right now I'm marking the point for each accessions position 
- I included the function of drag and drop to load the file of custom indicator (I just nedd to select the columns related with var "vars" into the function "calculate_sumary" in API)

**Comment by juangarc** [comment]
- [x] Allow filter accessions by taxonomy
- [x] Improve the information in the table of accessions
- [x] Add a view to get the detail for each accession in the table
- [x] Allow to see the information of the accessions when the user does click in the point of map
- [x] Allow the user can choices multiple parameters in the accessions form

**Comment by stevensotelo** [comment]
@juangarc 

- The app is showing the accessions into a map
- The app has the button to import custom data
- The app allow filter by taxa
- The list of the results was fixed
- The app allows to see detail of each accession
- The map is interactive with the user
- Users can select many indicators and parameters in the website when they are searching data
- [x] He should add button to see details of accession in the map

The issue of analogues is in stand by

**Comment by stevensotelo** [comment]
@juangarc 

- The plots are ready (line and density)
- [x] He should add two fields in the web interfaces: MinPts and epsilon
- [x] He should implement the subsets DB
- [x] He should add button to see details of accession in the map

**Comment by stevensotelo** [comment]
@juangarc
- He added button to see details of accession in the map
- [x] Add a loading image when the app is working
- [x] It should show message with No data (for example Maize and wild)
- [x] When filter accessions add a summary with amount of accessions found
- [x] Remove letters in autocomplete control
- [x] Check the plots
- [x] Remove button get accessions - Reduce the complexity of click. The users just should do click in get filter
- [x] Add new tab for indicator for crops
- [x] If the accessions don't have coordinates don't show map in detail windows
- [x] add new tab of summary (the output should be for crop): total accessions, total accessions filtered, total number of cluster, total accessions for each cluster
- [x] Join table, map, plots in one tab (general)
- [x] Add Cluster tab: Add cluster summary: include the values of each cluster (min, max, avg) per crop and per indicator. map with different color for accessions of each group. Add the accessions list with cluster data into a table with information for each crop and indicator and cluster

**Comment by stevensotelo** [comment]
@juangarc 
- Added a loading image when the app is working
- It should show message with No data (for example Maize and wild)
- When filter accessions add a summary with amount of accessions found
- Remove letters in autocomplete control
- Check the plots
- Remove button get accessions - Reduce the complexity of click. The users just should do click in get filter
- Add new tab for indicator for crops
- If the accessions don't have coordinates don't show map in detail windows
- add new tab of summary (the output should be for crop): total accessions, total accessions filtered, total number of cluster, total accessions for each cluster
- Join table, map, plots in one tab (general)
- [x] He should add two fields in the web interfaces: MinPts and epsilon
- [x] He should implement the subsets DB
- [x] Add Cluster tab: Add cluster summary: include the values of each cluster (min, max, avg) per crop and per indicator. map with different color for accessions of each group. Add the accessions list with cluster data into a table with information for each crop and indicator and cluster

**Comment by stevensotelo** [comment]
@juangarc
- He added two fields in the web interfaces: MinPts and epsilon
- He developed the cluster tab
- [x] He is implementing subsets DB in the web app
- [x] He is merging the multivairable analysis with accessions (cells ids)

**Comment by stevensotelo** [comment]
@juangarc 

- He is implementing subsets DB in the web app
- He is merging the multivairable analysis with accessions (cells ids)
