### ISSUE TITLE
New function for cleaning geographic data of accessions

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#46]
Before to import accessions into the database, we should validate which ones have good coordinates or bad coordinates, then we should add a new flag for those accessions into the database.

- [x] Compare with limits of latitude and longitude 
- [x] Compare with shapefile or raster if the point are in water or land

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- [x] She is still working on this.

**Comment by khadijaAouzal** [comment]
I found **CoordinateCleaner**, a package that cleans and validates coordinates data. 

I think it's better to use the functions of that package for our case.

The functions that we could use are:

- **cc_val**
- **cc_sea**
- **cc_equ**

You can see [their github repo](https://github.com/ropensci/CoordinateCleaner) for more details.

**Comment by stevensotelo** [comment]
Task didn't review

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She developed a function to validate data. Add new column flag type, it says if records are correct or bad. It says which is the problem.
- She tested for different cases

@juangarc 

- [x] He should implement this function into master script #25

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- [x] She will put the function into get passport data function

@juangarc

- [x] He should implement this function into master script

**Comment by khadijaAouzal** [comment]
Link to download the shapefile:
https://osmdata.openstreetmap.de/download/land-polygons-complete-4326.zip

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She implemented the function into the passport data function
- [x] She should share the url of the shapefile

@juangarc 

- [x] He should rerun the analysis.

**Comment by stevensotelo** [comment]
@khadijaAouzal 
- She sent the file

@juangarc 
- He is running the process again. For now are just two crops pending
