### ISSUE TITLE
Import generic indicator to database

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#49]
This task comes from #43 

|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|ndws|Ready|Ready|Ready|Ready|Ready|Ready|
|ndwlReady|Ready|Ready|Ready|Ready|Ready|Ready|
|p95|Ready|Ready|Ready|Ready|Ready|Ready|
|t_rain|Ready|Ready|Ready|Ready|Ready|Ready|
|tn|Ready|Ready|Ready|Ready|Ready|Ready|
|tx|Ready|Ready|Ready|Ready|Ready|Ready|
|sr|Ready|Ready|Ready|Ready|Ready|Ready|
|nvpd 4|Ready|Ready|Ready|Ready|Ready|Ready|
|vpd|Ready|Ready|Ready|Ready|Ready|Ready|
|cdd|Ready|Ready|Ready|Ready|Ready|Ready|
|dl|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Add the comment about the decision takken, in which you explain why you did it
- [x] Create a table similar to passport indicator. It will allow us to follow the progress in this task

**Comment by juangarc** [comment]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|ndws|||----|----|---||
|ndwl|||----|----|----||
|p95|Ready|Ready|Ready|Ready|Ready|Ready|
|t_rain|Ready|Ready|Ready|Ready|Ready|Ready|
|tn|||||||
|tx|||||||
|sr|||||||
|nvpd 4|||||||
|vpd|||||||
|cdd|Ready|Ready|Ready|Ready|Ready|Ready|
|dl|||||||

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/119142479-2c449c80-ba0c-11eb-8852-38303c13ba01.png)

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Still is pending: Add the comment about the decision takken, in which you explain why you did it
- He created a table similar to passport indicator. It will allow us to follow the progress in this task

**Comment by stevensotelo** [comment]
@juangarc 

- [x] Still is pending: Add the comment about the decision takken, in which you explain why you did it
- [x] He is running again the import process

**Comment by juangarc** [comment]
The reason why I changed the structure of the collection in the DB was thinking about the amount of data that must be stored in this collection, while in the previous model I had to store 12 records for each pixel for each indicator for each year, now I am storing a record with all 12 values.

Current model.
![image](https://user-images.githubusercontent.com/36042734/120473022-33549e80-c36c-11eb-9972-8a28f61abb77.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/120805112-07bbea80-c50b-11eb-948f-ba045980d645.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121361503-f869e200-c8fa-11eb-87fc-2cb78a7b31fb.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121691704-eae46180-ca8c-11eb-9394-ac798c5a7ff9.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/122224785-0fb84a80-ce7a-11eb-810d-4ebea4a6e37e.png)

**Comment by stevensotelo** [comment]
@juangarc 

- [ ] He should add the new indicators into database

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125952547-11cea8a8-b6c7-4047-8290-37432966b8e1.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/126785664-6fac2cd8-0f9c-40f0-a176-e5fd6fa21639.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/128515594-d1333fec-2f19-42cb-a47d-0ba5cdd79364.png)

**Comment by juangarc** [comment]
Today I will continue with the import

**Comment by stevensotelo** [comment]
We should restart importation process
