### ISSUE TITLE
Processing extracted value indicator

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#50]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Ph|Ready|Ready|Ready|Ready|Ready|Ready|
|Texture|Ready|Ready|Ready|Ready|Ready|Ready|
|BLDFIE|Ready|Ready|Ready|Ready|Ready|Ready|
|CECSOL|Ready|Ready|Ready|Ready|Ready|Ready|
|ORCDRC|Ready|Ready|Ready|Ready|Ready|Ready|
|Salinity|---|---|---|---|---|---|

**Comment by stevensotelo** [comment]
@bmora-0110 

- He has some indicators ready (ph, soil texture)
- [x] It is pending to create the table to follow the progress

@juangarc 

- [ ] <s>He should import data into the database</s>

**Comment by bmora-0110** [comment]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Ph|Ready|Ready|Ready|Ready|Ready|Ready|
|Texture|Ready|Ready|Ready|Ready|Ready|Ready|
|BLDFIE|---|---|---|---|---|---|
|CECSOL|---|---|---|---|---|---|
|ORCDRC|---|---|---|---|---|---|
|AWCh3|---|---|---|---|---|---|

**Comment by bmora-0110** [comment]
Soil properties, namely, USDA texture class (TEXMHT), bulk density (BLDFIE), cation exchange capacity (CECSOL), organic carbon content (ORCDRC), pH in H2O (PHIHOX), and water holding capacity at suction potential (pF) 2.5 (AWCh3). We calculate all properties as averages until 60 cm.

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121361067-91e4c400-c8fa-11eb-8143-fe733785fe26.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121691482-a789f300-ca8c-11eb-996c-f6cc6ab2fa01.png)

**Comment by stevensotelo** [comment]
@bmora-0110 
- [x] It is still pending to advance

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/123429801-feafbd80-d58c-11eb-9c08-46bb9c328561.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/124279845-940efc80-db0d-11eb-8f9b-168532d8ebfe.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125082292-a7c9de00-e08c-11eb-9409-ea6c91d1dd50.png)

**Comment by stevensotelo** [comment]
@stevensotelo 
- [x] He should share the script to search data in access file with @bmora-0110

**Comment by stevensotelo** [comment]
@stevensotelo 
- He sent the script to @bmora-0110 https://github.com/stevensotelo/rscripts/tree/master/access

![image](https://user-images.githubusercontent.com/4921829/125953294-e6246214-02eb-4ba3-ba46-c83c93772f30.png)

**Comment by stevensotelo** [comment]
We finished the most of the indicators. However we don't have a good database for salinity
