### ISSUE TITLE
Specific per crop indicator process

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#51]
|Crop|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Beans|Ready|Ready|Ready|Ready|Ready|Ready|
|Forages|Not possible|Not possible|Not possible|Not possible|Not possible|Not possible|
|Cassava|Ready|Ready|Ready|Ready|Ready|Ready|
|Banana|Ready|Ready |Ready|Ready|Ready|Ready|
|Wheat|Ready|Ready|Ready|Ready|Ready|Ready|
|Maize|Ready|Ready|Ready|Ready|Ready|Ready|
|Potato|Ready|Ready|Ready |Ready|Ready|Ready|
|Sweet potato|Ready|Ready|Ready|Ready|Ready|Ready|
|Andean crops|---|---|---|----|---|---|
|Rice|Ready |Ready |Ready  |Ready |Ready |Ready |
|Barley|Ready|Ready|Ready|Ready|Ready|Ready|
|Sorghum|Ready|Ready|Ready|Ready|Ready|Ready|
|Pearl Millet|Ready|Ready|Ready|Ready|Ready|Ready|
|Cowpea|Ready|Ready|Ready|Ready|Ready|Ready|
|Yam|Ready|Ready|Ready|Ready|Ready|Ready|
|Soybean|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
@bmora-0110 

- Yam is done
- [x] He should update the table

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121361897-4a126c80-c8fb-11eb-9f21-c0d9c90df150.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] Create a table with the list of the indicators for each crop and their limits https://github.com/CIAT-DAPA/subsets_genebank_accessions/wiki/Indicators-per-crop

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121691841-11a29800-ca8d-11eb-921f-71a335867693.png)

**Comment by stevensotelo** [comment]
@bmora-0110 
- [x] Include description Heat_stress, Cold_stress, Optimum in the following webpage https://github.com/CIAT-DAPA/subsets_genebank_accessions/wiki/Ontologies

**Comment by stevensotelo** [comment]
@bmora-0110 
- Potato and Beans are done
- He created the table with description
- [x] He should talk with Julian about some range which are too high.

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/123430119-6e25ad00-d58d-11eb-8732-88898f60ae53.png)

**Comment by stevensotelo** [comment]
@jramirezv  said that is ok if we get many zeros in the indicators for crops

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/124280005-c7518b80-db0d-11eb-813b-6ca9b95fe9df.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125082533-f4151e00-e08c-11eb-80cb-071734e188c4.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125953690-b5e2e895-4797-4ea1-ac5b-a670cd557078.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [ ] Sent the list of the metrics that you need to @khadijaAouzal 
- [ ] For Andean crops just work with Andean countries. The baseline should be potato + genesys (South america)

@khadijaAouzal 

- [ ] She will figure out data for barley and  soybean

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/126786013-095f4dce-f5d7-436f-b08d-73f6c6f9947b.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

- [x] Sent the list of the metrics that you need to @khadijaAouzal 
- [x] For Andean crops just work with Andean countries. The baseline should be potato + genesys (South america)

@khadijaAouzal 

- [ ] She will figure out data for barley and  soybean

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/128515668-0ee903b2-cedf-43d5-bbef-59e238f02f21.png)

**Comment by stevensotelo** [comment]
@bmora-0110 
- He sent the list of the metrics to @khadijaAouzal 
- [ ] He is creating the baseline for andean crops in country level + genesys accessions

@khadijaAouzal 
- She asked for the information
- [ ] She will ask again for information for the crops

**Comment by juangarc** [comment]
![image](https://user-images.githubusercontent.com/36042734/129361696-def637e8-4e5e-43be-af3c-56be6fda335c.png)

**Comment by juangarc** [comment]
He has issue with the script, He is improving it, the he share with @juangarc the new structure for the indicators.

- [x] He should check the crop area in the crops:
- Forages
- Rice
- Wheat
- Pearl Millet
- Maize

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/131131975-b372fc88-0282-43ae-8e3a-4f75763c5d41.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/131849121-735eb1b4-b33f-4e36-9884-4f3de9e3afd4.png)
