### ISSUE TITLE
Import specific per crop indicators to database 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#56]
|Crop|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Beans|Ready|Ready|Ready|Ready|Ready|Ready|
|Forages|---|---|----|----|----|---|
|Cassava|Ready|Redy|Ready|Ready|Ready|Ready|
|Banana|Ready|Ready|Ready|Ready|Ready|Ready|
|Wheat|Ready|Ready|Ready|Ready|Ready|Ready|
|Maize|Ready|Ready|Ready|Ready|Ready|Ready|
|Potato|Ready|Ready|Ready|Ready|Ready|Ready|
|Sweet potato|Ready|Ready|Ready|Ready|Ready|Ready|
|Andean crops|---|---|---|----|---|---|
|Rice|Ready|Ready|Ready|Ready|Ready|Ready|
|Barley|Ready|Ready|Ready|Ready|Ready|Ready|
|Sorghum|Ready|Ready|Ready|Ready|Ready|Ready|
|Pearl Millet|Ready|Ready|Ready|Ready|Ready|Ready|
|Cowpea|Ready|Ready|Ready|Ready|Ready|Ready|
|Yam|Ready|Ready|Ready|Ready|Ready|Ready|
|Soybean|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
@bmora-0110 

- The crops Yam and cassava are ready.
- [x] He is working on it. He is changing the format in order to @juangarc can import data into database. It is for beans and potato.

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/123430483-daa0ac00-d58d-11eb-8a2b-0d2fd645ba4a.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125083058-89181700-e08d-11eb-83cd-6baacdc084a4.png)

**Comment by stevensotelo** [comment]
We estimate that for 31 July, we will have all data imported

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125954882-8a92d258-7bc6-424b-b87b-cf66dca272ab.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/126786294-28ede410-568b-4436-91c5-ac276972c33f.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/128516347-804e6542-453a-4bc6-aa4e-769bb8c219bf.png)

**Comment by juangarc** [comment]
![image](https://user-images.githubusercontent.com/36042734/129362483-3fae8a17-7e1a-467c-a548-e925b859cbb5.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/130237879-d5bd249d-58c2-4a53-8a92-d36e8d6806f9.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/133787108-187e6efd-a125-465e-ae67-908d7afbc051.png)

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] Restart the importation process of the data

**Comment by stevensotelo** [comment]
We should restart importation process
