### ISSUE TITLE
Import extracted value indicator to database

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#57]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Ph|---|---|---|---|---|---|
|Texture|---|---|---|---|---|---|
|BLDFIE|Ready|Ready|Ready|Ready|Ready|Ready|
|CECSOL|Ready|Ready|Ready|Ready|Ready|Ready|
|ORCDRC|Ready|Ready|Ready|Ready|Ready|Ready|
|AWCh3|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/121693947-3861ce00-ca8f-11eb-94c1-852292f36493.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/122226372-89046d00-ce7b-11eb-9371-fe744343d69a.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/123429974-37e82d80-d58d-11eb-873c-baea1c9d194d.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125082455-dba50380-e08c-11eb-8a7e-d0a81f8d44e0.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/125952721-1cc57a22-3a44-4aff-8732-6b7975a8dbfe.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/126785914-52d83141-ba20-4c4f-a407-9e2ac8afa4ca.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/128515482-f37dac45-be90-4953-a0c5-144a055d6081.png)

**Comment by juangarc** [comment]
Today I will continue with the import

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] Set available all this indicators in the list of the website

**Comment by stevensotelo** [comment]
We should restart importation process
