### ISSUE TITLE
Implement hierarchy clustering 

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#58]
@khadijaAouzal 
- [x] Develop a method to build a method

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She is exploring information about how we can do
- [x] She will compare the two algorithms HDBScan and agglomerative 

@bmora-0110 

- He checked the DBScan Hierarchy

**Comment by stevensotelo** [comment]
@khadijaAouzal

- She compared the two algorithms HDBScan and agglomerative
- [x] She will send output data to @bmora-0110 
- [x] She develop a function which include HDBSCan and agglomerative. The function 

![image](https://user-images.githubusercontent.com/4921829/124283111-2795fc80-db11-11eb-86e2-cfcc6bac5579.png)

@bmora-0110 
- [x] He will check the outputs of the algorithms and give us his thoughts

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She sent the data to @bmora-0110 
- She develop the function 
- [x] She is debugging the function and then she will upload the function to github
 
@bmora-0110 
- He checked the data. 
- [x] He will write the questions here

**Comment by stevensotelo** [comment]
@bmora-0110
- [x] He will write the questions here

@khadijaAouzal 
- She developed the function and uploaded the script

**Comment by bmora-0110** [comment]
Kjadija, I have some comments here:

1 . We are going to implement two methodologies DBSCAN and HDBSCAN, I understand that the methodologies are different but, I consider that the results should be more or less similar. So I think it would be important to do a test if this is really true.

2. There is a term in the algorithms called "Border points" and in our case they are accessions that will not belong to any cluster, I think this would be fine for DBSCAN, but for HDBSCAN, I consider that it is of great importance that all the accessions are included in the different clusters.

Thanks.

**Comment by stevensotelo** [comment]
We continue with the discussion and we will wait for the comments from users to define hyper parameters

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She developed the function
