### ISSUE TITLE
Define limits for indicator in the website

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#60]
@juangarc 
- [x] He should define the range of filter for each indicator, according to the accessions values (min and max). The process is: Filter accessions selected by user, then he should search in the summary of the indicators what are the limits for them, just min and max value

![image](https://user-images.githubusercontent.com/4921829/121704324-461c5100-ca99-11eb-9943-768ec56691df.png)

**Comment by juangarc** [comment]
This issue is pending

**Comment by stevensotelo** [comment]
We stopped this issue because we need space in the server to import summaries

**Comment by stevensotelo** [comment]
It was implemented
