### ISSUE TITLE
Import summaries to the database

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#61]
@juangarc 

- [ ] He should import summaries of  indicators into the database

**Comment by stevensotelo** [comment]
@bmora-0110 
- He sent data to @juangarc 

@juangarc 
- [ ] He should start importing data to database

**Comment by juangarc** [comment]
This issue is pending

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] Restart importation data to database

**Comment by juangarc** [comment]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|ndws|Ready|Ready|Ready|Ready|Ready|Ready|
|ndwlReady|Ready|Ready|Ready|Ready|Ready|Ready|
|p95|Ready|Ready|Ready|Ready|Ready|Ready|
|t_rain|Ready|Ready|Ready|Ready|Ready|Ready|
|tn|Ready|Ready|Ready|Ready|Ready|Ready|
|tx|Ready|Ready|Ready|Ready|Ready|Ready|
|sr|Ready|Ready|Ready|Ready|Ready|Ready|
|nvpd 4|Ready|Ready|Ready|Ready|Ready|Ready|
|vpd|Ready|Ready|Ready|Ready|Ready|Ready|
|cdd|Ready|Ready|Ready|Ready|Ready|Ready|
|dl|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/136562049-519cc550-9ee3-4ebf-bdb5-af8c7ca384f3.png)

**Comment by stevensotelo** [comment]
@juangarc 

- He checked the quality data into database
