### ISSUE TITLE
HUS006 - Build custom indicators

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#7]
**Description**

As an user, I want to be able build a set of custom indicators for each accession from a file previously loaded in the tool, with which latterly the users will may to create Genebank accessions subsets from filters based in them.

**Acceptance criteria**

- [ ] **Stage 1 – Load custom indicators file:** To build a custom indicator the user must have a file with the following fields: id taxonomy or taxonomy name, indicator (which will add the value) and the indicator value, once him filled out it will proceed to select it in the section custom indicators, the user will run the script that build the custom indicators. 
- [ ] **Stage 2 - Successful operation:** For each stage, if the operation flow is successful the system shows a message indicating it.    
- [ ] **Stage 3 - Failed operation:** For each stage, if the file structure isn't correctly, the system will show an exception with the message: "The file structure isn't correct."       
- [ ] **Stage 4 - Missing value:** For each stage, if the file has a column without value, the indicator for this accession won't create.           
- [ ] **Stage 5 - Generate logs file:** For each stage the system will generates a log file, which is described in the HUS007.

**Comment by khadijaAouzal** [comment]
@juangarc @stevensotelo
As we discussed it before, the custom indicators will not be stored. They will be used only during the session of the user who uploaded them.  
The aim of this process is to bind custom data to accessions, previously extracted, using the accession id, right? For that, what should the uploaded file format be? and the result format?

**Comment by stevensotelo** [comment]
@khadijaAouzal 

We haven't defined how should be the file format for custom indicators. I consider the following

- [ ]  Id of accession (Genesys ID) have to be mandatory field
- [ ]  Define how many variables this file should have (max. numbers of variables)

Other issues that I consider that we need to define are the following

- [ ] Methodology to calculate indicators (PCA or which one ). We should define a set of metrics that we can calculate

Note

- [ ] The function to calculate custom indicators should be a class or function in Python which @juangarc can implement inside of the Web API

@juangarc 

- [x] add the metrics which were asked for users

**Comment by juangarc** [comment]
The metrics available are: median, arithmetic average, quartiles, percentiles (5, 95) and standard deviation.
