### ISSUE TITLE
Generate plot in website for each generic indicator summary

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#75]
Implement a function on the website that generates a plot for each indicator selected by the user with the summary data, this plot must contain five lines: 
- Average
- Min
- Max
- Quartile 25
- Quartile 75

**Comment by juangarc** [comment]
@brayan9487
- [ ]  Generate the summary data for each generic indicator.

@juangarc 
- [ ]  Import data into the database.
- [ ] Implement service that allows to query and calculate the summary data for each indicator selected by the users
- [ ] Implement the line plot with the five lines (Avg, min, max, quartile 25, quartile 75)

**Comment by stevensotelo** [comment]
It changed with new issues
