### ISSUE TITLE
Check countries and coordinates

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#77]
Some accessions looks in different country:

![image](https://user-images.githubusercontent.com/4921829/125958610-596babd0-3d57-4aeb-b3fd-4b0799436159.png)

**Comment by khadijaAouzal** [comment]
Here is the result I get, from `get_passport_data()`, for Beans in Mexico

![image](https://user-images.githubusercontent.com/23177635/125978915-aa952c7a-9446-418e-92d8-21159cc5ade6.png)

**Comment by stevensotelo** [comment]
<s>@juangarc 
- [x] Check what is going wrong with some accessions

@khadijaAouzal 
- [x] She'll send the data about which accessions are in wrong country
</s>
This issues was solved
