### ISSUE TITLE
Check where the summaries are

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#81]
@bmora-0110 

- [x] He should search where the summaries for min and max

**Comment by bmora-0110** [comment]
I have the data in another folder, I tried to put it in the workspace but I don't have permissions. I already sent an email to Jorge to talk about solving this problem.

**Comment by stevensotelo** [comment]
@bmora-0110 

- He sent the location to @juangarc
