### ISSUE TITLE
Estimate the Hyperparameters for hierarchical clustering

### ISSUE THREAD

**Issue by khadijaAouzal** [CIAT-DAPA/subsets_genebank_accessions#83]
@bmora-0110 suggested a method to estimate the distance threshold for hierarchical clustering algorithm. The method uses PCA and eigenvalues.

@khadijaAouzal 

- [x] will explore the proposed method.

**Comment by juangarc** [comment]
@bmora-0110 shares the data con @khadijaAouzal 

@bmora-0110 

- [x] Share with @khadijaAouzal more information 

@khadijaAouzal 

- [x] will explore the proposed method

**Comment by stevensotelo** [comment]
@bmora-0110 
- [x] He search information about this topic

**Comment by stevensotelo** [comment]
@bmora-0110 

- He sent the information of the website to @khadijaAouzal 

@khadijaAouzal 

- She checked the information
- [ ] She explorer a new method for estimating hyper parameters

**Comment by stevensotelo** [comment]
We continue think on it

A possible solution would set a number for maximum number of clusters like this:
![image](https://user-images.githubusercontent.com/4921829/136567579-26eb2b2d-9e72-4bca-b9a3-764009ed5785.png)

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She did it
