### ISSUE TITLE
Add Methodology tab in the website

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#86]
@khadijaAouzal 

- [x] Search information about methodologies used in the tool
- [x] Share information with @juangarc 

@juangarc 

- [x] Add methodology tab in navbar of website
- [x] Add information in the new tab shared by @khadijaAouzal

**Comment by stevensotelo** [comment]
@juangarc 
- [x] He create the new web page

**Comment by stevensotelo** [comment]
@khadijaAouzal 

- She send prepared and sent the information to @juangarc 

@juangarc 

- [x] Add information in the new tab shared by @khadijaAouzal

**Comment by stevensotelo** [comment]
They finished it
