### ISSUE TITLE
Test Website

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#88]

**Comment by khadijaAouzal** [comment]
**Crop**: _african yam bean_
**Indicators**: _extreme daily precipitation_ and _total precipitation_
**Values ranges**: [0:300] for both indicators
**Years**: 1983 - 2017
**Months**: Jan - Dec

**Issue**: the query results in empty data 
![image](https://user-images.githubusercontent.com/23177635/132000875-a278b4d7-851d-4bd1-9941-d51999a0b9b0.png)

**Comment by khadijaAouzal** [comment]
**Crop**: _african yam bean_
**Indicators**: _consecutive dry days_ and _average maximum temperature_
**Values ranges**: [0:300] for both indicators
**Years**: 1983 - 2017
**Months**: Jan - Dec

**Issues**:

![image](https://user-images.githubusercontent.com/23177635/132010023-9f56df2c-f34b-4e5d-b792-d4721dc943c1.png)
  I explored the data and found some problems:

- The data of 2017 are not included. This is the cause of the above issue, as the expected number of years is 35 while the data cover 34 years (from 1983 to 2016). 
- Only the average maximum temperature data are in the response, the consecutive dry days data are not extracted.

**Comment by bmora-0110** [comment]
- I made a simple filter for maize in Colombia, with a maximum temperature of 15 - 30, the page loaded as 5 min and did not show any results.

- I also tested the above for total precipitation and CDD but I could not obtain anything.

**Comment by khadijaAouzal** [comment]
The default value of the number of clusters, i.e. 5, for hierarchical agglomerative clustering, is always passed even if we change the value

**Comment by juangarc** [comment]
> The default value of the number of clusters, i.e. 5, for hierarchical agglomerative clustering, is always passed even if we change the value

Issue solved

**Comment by juangarc** [comment]
> The default value of the number of clusters, i.e. 5, for hierarchical agglomerative clustering, is always passed even if we change the value

Issue solved

**Comment by juangarc** [comment]
> **Crop**: _african yam bean_
> **Indicators**: _extreme daily precipitation_ and _total precipitation_
> **Values ranges**: [0:300] for both indicators
> **Years**: 1983 - 2017
> **Months**: Jan - Dec
> 
> **Issue**: the query results in empty data
> ![image](https://user-images.githubusercontent.com/23177635/132000875-a278b4d7-851d-4bd1-9941-d51999a0b9b0.png)

Issue solved
![image](https://user-images.githubusercontent.com/36042734/134672590-8ca81288-5641-46fd-9a2d-aa4b64bc6c7d.png)

**Comment by juangarc** [comment]
> * I made a simple filter for maize in Colombia, with a maximum temperature of 15 - 30, the page loaded as 5 min and did not show any results.
> * I also tested the above for total precipitation and CDD but I could not obtain anything.

Issue solved
![image](https://user-images.githubusercontent.com/36042734/134673024-5b307fbc-c89b-4dd3-b126-cc72a227dd25.png)

![image](https://user-images.githubusercontent.com/36042734/134673264-6bfbac54-e4de-43d3-a600-61d9e166fada.png)
