### ISSUE TITLE
Indicators_temp_andean_crops

### ISSUE THREAD

**Issue by bmora-0110** [CIAT-DAPA/subsets_genebank_accessions#89]
Processing

**Comment by bmora-0110** [comment]
|Crop|Status|
|---|---|
|Achiras|Ready|
|Arracacha|Ready|
|Jicama|Ready|
|Mashua|Ready|
|Mauka|Ready|
|Ulluco|Ready|
|Yacon|Ready|
|Maca|Ready|
|Oca|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/133786999-f902149f-238c-4749-826c-59a575353777.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/134679507-5b23bcae-7fdc-4827-badf-413188e94a31.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/136561994-94655252-4794-4451-85b1-76986f713954.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/137491511-41243596-9f8b-4069-b86b-bd0894c8d95c.png)
 Jicama, Mauka and Ulluco are ready

Now we are running Yacon, Maca and Oca

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/138458133-7a43eee9-5a2b-411a-893a-20bdfc1e1ec6.png)

**Comment by stevensotelo** [comment]
@bmora-0110 

The indicators were calculated, however we are waiting for changing the output format

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/140516013-85c22503-ddfc-48a6-a05e-1e3b45267dc1.png)
