### ISSUE TITLE
Import generic indicator to database

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#90]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|ndws|Ready|Ready|Ready|Ready|Ready|Ready|
|ndwl|Ready|Ready|Ready|Ready|Ready|Ready|
|p95|Ready|Ready|Ready|Ready|Ready|Ready|
|t_rain|Ready|Ready|Ready|Ready|Ready|Ready|
|tn|Ready|Ready|Ready|Ready|Ready|Ready|
|tx|Ready|Ready|Ready|Ready|Ready|Ready|
|srad|Ready|Ready|Ready|Ready|Ready|Ready|
|nvpd 4|Ready|Ready|Ready|Ready|Ready|Ready|
|vpd|Ready|Ready|Ready|Ready|Ready|Ready|
|cdd|Ready|Ready|Ready|Ready|Ready|Ready|
|dl|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/136562829-dead5909-16e2-46da-8bce-8cef24688d03.png)

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/137491690-25488c97-4b59-466f-9ac3-da0a8d82eaed.png)

nvpd4 and vpd are ready

Now we are running ndws and ndwl

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/138458213-84799e6d-fea5-4bb8-997c-d44ef9adc75b.png)
