### ISSUE TITLE
Import specific per crop indicators to database

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#91]
|Crop|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Beans|Ready|Ready|Ready|Ready|Ready|Ready|
|Cassava|Ready|Ready|Ready|Ready|Ready|Ready|
|Banana|Ready|Ready|Ready|Ready|Ready|Ready|
|Wheat|Ready|Ready|Ready|Ready|Ready|Ready|
|Maize|Ready|Ready|Ready|Ready|Ready|Ready|
|Potato|Ready|Ready|Ready|Ready|Ready|Ready|
|Sweet potato|Ready|Ready|Ready|Ready|Ready|Ready|
|Andean crops|Ready|Ready|Ready|Ready-|Ready|Ready|
|Rice|Ready|Ready|Ready|Ready|Ready|Ready|
|Barley|Ready|Ready|Ready|Ready|Ready|Ready|
|Sorghum|Ready|Ready|Ready|Ready|Ready|Ready|
|Pearl Millet|Ready|Ready|Ready|Ready|Ready|Ready|
|Cowpea|Ready|Ready|Ready|Ready|Ready|Ready|
|Yam|Ready|Ready|Ready|Ready|Ready|Ready|
|Soybean|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/136562645-0976942c-9732-4585-80ca-c6084ee19481.png)

**Comment by stevensotelo** [comment]
@juangarc 

- He checked the quality into the database
