### ISSUE TITLE
Import extracted values indicators to database

### ISSUE THREAD

**Issue by juangarc** [CIAT-DAPA/subsets_genebank_accessions#92]
|Indicator|Europe |Oceania|Asia|North America|South America|Africa|
|---|---|---|---|---|---|---|
|Ph|Ready|Ready|Ready|Ready|Ready|Ready|
|Texture|Ready|Ready|Ready|Ready|Ready|Ready|
|BLDFIE|Ready|Ready|Ready|Ready|Ready|Ready|
|CECSOL|Ready|Ready|Ready|Ready|Ready|Ready|
|ORCDRC|Ready|Ready|Ready|Ready|Ready|Ready|
|AWCh3|Ready|Ready|Ready|Ready|Ready|Ready|

**Comment by stevensotelo** [comment]
![image](https://user-images.githubusercontent.com/4921829/136562281-e6a8e940-fd85-41b8-9618-55781ff8bb4b.png)

**Comment by stevensotelo** [comment]
@juangarc 
- He checked database quality
