### ISSUE TITLE
Run simulation for optimal number of clusters

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/subsets_genebank_accessions#99]

**Comment by khadijaAouzal** [comment]
@stevensotelo @bmora-0110 Could you please provide a description for that?

**Comment by stevensotelo** [comment]
@khadijaAouzal:

I think that with this method, the algorithm will never converge to one value, as at each time we move the window of the range

 In each time we may get new optimal number or the same number as the closest pervious ranges

here is an example, where the range starts with [2,5] and moved forward, at each run, with 1 at its both bounds until the upper bound reaches 100

![image](https://user-images.githubusercontent.com/4921829/138458690-c1f6e697-fc86-434b-85d4-52f5994c8af5.png)

![image](https://user-images.githubusercontent.com/4921829/138458765-54a6ccc2-c2f2-4b8b-96ff-3338d17ed3c4.png)
